title: I Encontro Estadual AMM - SP
email: comunicacao@amm-brasil.org
description: Primeiro Encontro Estadual dos AMM de São Paulo que ocorrerá de 12 a 14 de janeiro de 2018 em Indaiatuba - SP
baseurl: ""
url: ""
twitter_username:
github_username:  amm-brasil
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
